mollie/PrestaShop

- mollie/mollie.php
- tests/unittests/mollieTest.php
Commits from #19. Also fixes test.
> Check for hook existence at install/uninstall

- mollie/mollie.php
As it would be nice to be able to style the return messages an id attribute is necessary.  Thanks!
> id ifv css

- mollie.php
- views/js/apple_payment.js
- views/js/method_countries.js
> changed module version and added licenses

- controllers/front/payment.php
- controllers/front/return.php
Order total paid real is only added on status paid now
> MOL-435 order total paid real added on status paid

- changelog.md
- controllers/front/ajax.php
- mollie.php
- src/Adapter/ConfigurationAdapter.php
- src/Install/Installer.php
- src/Service/MailService.php
- src/Service/MolliePaymentMailService.php
- src/Service/OrderStatusService.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation/EnvironmentVersionSpecificPaymentMethodRestrictionValidator.php
- src/Service/TransactionService.php
- src/Utility/UrlPathUtility.php
Adding different check for PS 1.7.7.* to handle manual order creation using mollie payment.
> MOLIM-232/manual order creation

- views/css/mollie_iframe.css
- views/templates/hook/mollie_iframe.tpl
- views/templates/hook/mollie_iframe_16.tpl
Added expiry date label on checkout page
> MOL-273 expiry date label

- mollie.php
> Revert "fixed single click with compoments for ps16"

- changelog.md
- config/context.yml
- config/handler.yml
- src/Factory/ContextFactory.php
- src/Handler/PaymentOption/PaymentOptionHandler.php
- src/Service/ApiService.php
- src/Service/CustomerService.php
- src/Service/PaymentMethodService.php
- views/js/validation.js
> Revert "MOLIM-256: single click payment + components and env settings fix"

- src/Install/Installer.php
Added status re-creation after module reset functionality,
> MOLIM-287 status recreate after reset added

- src/Provider/UpdateMessageProvider.php
- views/templates/admin/github_redirect.tpl
- views/templates/admin/new_release.tpl
Update url link fix, link moved from php to tpl file.
> Update url link fix

- composer.lock
- mollie.php
- src/Adapter/ProductAttributeAdapter.php
- src/Service/MailService.php
- subscription/Handler/RecurringOrderCreationHandler.php
- subscription/Install/AttributeInstaller.php
- subscription/Install/AttributeUninstaller.php
- subscription/Validator/CanProductBeAddedToCartValidator.php
- subscription/Validator/SubscriptionProductValidator.php
- tests/phpstan/phpstan_base.neon
added attribute adapter and some small improvements
> PIPRES-6: improved validations and added atribute adapter

- views/css/front/subscription/customer_order_detail.css
- views/templates/front/subscription/customerRecurringOrderDetail.tpl
> Pipres 6/edit address

- .github/workflows/test.yml
- config/routes.yml
- src/Service/MailService.php
- subscription/Controller/Symfony/SubscriptionController.php
- subscription/Grid/SubscriptionGridDefinitionFactory.php
- subscription/Grid/SubscriptionGridQueryBuilder.php
Added subscription search and filter. Fixed filter errors. Also tried to fix automated test but with no luck. for now skipping it and will come back when main feature is done.
> PIPRES-6: added search and filter for subscriptions in admin page

- views/templates/front/subscription/customerAccount.tpl
- views/templates/front/subscription/customerRecurringOrderDetail.tpl
- views/templates/front/subscription/customerSubscriptionsData.tpl
https://mollie.atlassian.net/browse/PIPRES-210
> PIPRES-210: improved text

- controllers/front/payment.php
- src/Service/CustomerService.php
- src/Service/PaymentMethodService.php
- subscription/Controller/Symfony/SubscriptionFAQController.php
- subscription/Validator/SubscriptionOrderValidator.php
- views/templates/admin/Subscription/subscriptions-faq.html.twig
https://mollie.atlassian.net/browse/PIPRES-209
if subscription is being created we always use payment API
> PIPRES-209: use payment api all the time if subscription is used

- src/Install/Installer.php
> PIPREs-180: Duplicate partial refund order state fix

- .github/workflows/test.yml
- src/Adapter/Context.php
- src/DTO/OrderData.php
- src/Repository/GenderRepository.php
- src/Repository/GenderRepositoryInterface.php
- src/Service/CartLinesService.php
- src/Service/PaymentMethodService.php
- src/ServiceProvider/BaseServiceProvider.php
- src/Verification/Shipment/CanSendShipment.php
- tests/Integration/Subscription/Factory/TestCreateSubscriptionData.php
- tests/Integration/Subscription/Validator/SubscriptionCartTest.php
- tests/Unit/Provider/SubscriptionIntervalTest.php
Added optional parameters to be sent:
Title,
Product url,
Product image url,
ConsumerDateOfBirth
> PIPRES-202/optional parameters

- .github/workflows/deploy.yml
Suggestion was to not use 3rd party libs for deployment. Found another solution by writing all of the commands for secure connection manually.
> PIPRES-108: Auto deploy improvements

- .github/workflows/deploy.yml
- composer.json
- mollie.php
- src/Adapter/Context.php
- subscription/Install/HookInstaller.php
- subscription/Verification/HasSubscriptionProductInCart.php
also found out that sentry 3.18.0 version causes issues due to missing other library. Downgraded to 3.17.0 and added missing library. Now prestashop doesn't crash.
> PIPRES-218: Prevent guest to buy subscription item

- src/Service/ShipmentService.php
Deprecated property and removed since PS8
> PIPRES-219: Shipping number replacement

- controllers/admin/AdminMollieAjaxController.php
- src/Provider/PaymentFeeProvider.php
- src/Service/ApiService.php
- src/Utility/NumberUtility.php
- tests/phpstan/phpstan_base.neon
PrestaShop 1.7.6. uses older version of Number vendor package. Added condition to use available class based if it's extended by another.
> PIPRES-65: Conditional number of DecimalNumber usage

- controllers/admin/AdminMollieAjaxController.php
- src/Calculator/PaymentFeeCalculator.php
- src/Install/DatabaseTableInstaller.php
- src/Provider/PaymentFeeProvider.php
- src/Provider/PaymentFeeProviderInterface.php
- src/Service/ApiService.php
- src/Utility/NumberUtility.php
- tests/Mollie/Tests/Unit/Utility/NumberUtilityTest.php
- tests/Unit/Calculator/PaymentFeeCalculatorTest.php
- tests/Unit/Provider/PaymentFeeProviderTest.php
- upgrade/Upgrade-6.0.1.php
- views/js/validation.js
Improved fee calculation logic: moved logic to separate calculation service, which utilizes NumberUtility service for calculus actions. 
Additionally, fixed minor bugs for price rounding, variable naming.
P.S. Tests takes up half of written code, sorry. :D
> PIPRES-65: Tax rule select for percentage fee

- changelog.md
- controllers/admin/AdminMollieAjaxController.php
- mollie.php
- src/Service/ApiService.php
- src/Utility/NumberUtility.php
Rounding in set up process caused wrong prices due to too early rounding.
> PIPRES-268: Payment fee rounding improvements

- mollie.php
- src/DTO/PaymentData.php
- src/Service/ApiKeyService.php
- src/Service/MollieOrderCreationService.php
- src/Service/MollieOrderInfoService.php
- src/Service/MolliePaymentMailService.php
- src/Service/PaymentMethodService.php
For initial subscription order add different identifier to enable filter data more easily.
> PIPRES-260: Add different identifier for initial subscription order

- src/Repository/MethodCountryRepository.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation/AmountPaymentMethodRestrictionValidator.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation/ApplePayPaymentMethodRestrictionValidator.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation/BasePaymentMethodRestrictionValidator.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation/EnvironmentVersionSpecificPaymentMethodRestrictionValidator.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation/PaymentMethodRestrictionValidatorInterface.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation/VoucherPaymentMethodRestrictionValidator.php
- src/ServiceProvider/BaseServiceProvider.php
- tests/Unit/Service/PaymentMethod/PaymentMethodRestrictionValidation/ApplePayPaymentRestrictionValidationTest.php
Added missing dependency from validation script. Also added return types for validation methods.
> PIPRES-304: Payment method range limit fix

- subscription/Handler/RecurringOrderHandler.php
Order failed previously as passed total amount from Mollie included payment fee, while cart did not. We only add payment fee after order is created.
Using non loggable order state. This way order amount is not being checked.
> PIPRES-308: Recurring order with payment fee fix

- changelog.md
- mollie.php
- views/js/front/subscription/product.js
Fixed checking for existence of elements. Merchant has custom product page, which does not have specific data, required for subscription service to fully work. Fixed checks if data is missing from the page.
> PIPRES-138: Subscription add to cart front validation fix

- changelog.md
- mollie.php
- views/js/front/subscription/product.js
* PIPRES-138: Subscription add to cart front validation fix
* changelog and version bump
> Release-6.0.3

- subscription/DTO/SubscriptionOrderAmountProviderData.php
- subscription/Exception/CouldNotCreateSubscriptionData.php
- subscription/Exception/CouldNotProvideSubscriptionOrderAmount.php
- subscription/Exception/ExceptionCode.php
- subscription/Factory/CreateSubscriptionDataFactory.php
- subscription/Provider/SubscriptionOrderAmountProvider.php
- tests/Unit/BaseTestCase.php
- tests/Unit/Subscription/Factory/CreateSubscriptionDataFactoryTest.php
- tests/Unit/Subscription/Provider/SubscriptionOrderAmountProviderTest.php
This provider will be used in other service too so abstracted it to reduce code repetition.
> PIPRES-349: Abstract subscription order total provider

- views/templates/front/subscription/customerSubscriptionsData.tpl
correction of a spelling mistake
> Correction of a spelling mistake in customerSubscriptionsData.tpl

- src/Repository/OrderRepository.php
- src/Service/OrderStatusService.php
> PIPRES-363: Fixed case with split orders where status wasn't correct

- mollie.php
- src/Install/Installer.php
- src/Install/Uninstall.php
- subscription/Controller/Symfony/SubscriptionController.php
- subscription/Repository/RecurringOrderRepository.php
- views/templates/admin/Subscription/subscriptions-settings.html.twig
> PIPRES-349: Update carrier callers

- src/ServiceProvider/BaseServiceProvider.php
Dependencies conflict between third party modules fix
> PIPRES-431: league container conflict fix

- views/templates/admin/Subscription/subscriptions-settings.html.twig
Fixed dropdown to fit inside dedicated place in subscription back office tab
> PIPRES-413/dropdown in bo tab fix

- src/Service/PaymentMethodService.php
- views/templates/admin/_configure/helpers/form/form.tpl
Empty maximum fee will make this value unlimited
> PIPRES-410/ Maximum fee field

- views/templates/front/order-confirmation-table.tpl
- views/templates/hook/ideal_dropdown.tpl
> PIPRES-412/Bootstrap 5 compatibility improvements

- src/DTO/OrderData.php
- src/ServiceProvider/BaseServiceProvider.php
> PIPRES-431/ League Container fix

- src/Provider/PhoneNumberProvider.php
mobile phone fix then field is removed
> PIPRES-449: mobile phone fix then field is removed

- composer.json
- src/ServiceProvider/PrestashopContainer.php
> Revert "PIPRES-443/ League container version bump"

- mollie.php
- src/Install/Installer.php
- subscription/Install/Installer.php
Some users are unable to install/upgrade module. To get more information logs has been added to check where installation fails.
> PIPRES-442/ logs added to track installation progress

- src/ServiceProvider/BaseServiceProvider.php
Fixed apple pay on express checkout processing
> apple pay fix

- subscription/Provider/SubscriptionStartDateProvider.php
Solve https://github.com/mollie/PrestaShop/issues/965
> Go through all combination attributes to check subscription interval

- src/Config/Config.php
- src/DTO/PaymentData.php
- src/Service/PaymentMethodService.php
ALMA payment method allows order api
> PIPRES-473/alma order api

- src/Config/Config.php
> PIPRES-483/ satispay payment method added

- src/Config/Config.php
> PIPRES:482/paybybank payment method added

- src/Provider/PhoneNumberProvider.php
…Mollie expects
| Branch?         | Release-6.2.5
| Description?    | hone number will now have more strict rules to have E.164 format
| Type?           | bug fix 
| How to test?    | Use different phone formats. Non E.164 format will not send phone number
> PIPRES-469 Phone number will now have more strict rules to have E.164 format

- src/Install/OrderStateInstaller.php
| Branch?         | Release
| Description?    | Fixed arguments for state installation
| How to test?    | Install module on any shop context. All states must be installed correctly and values must be stored correctly in configuration table
| Fixed issue ?   | PIPRES-495
> PIPRES-495 fixed multi shop order state

- cypress/e2e/ps8/03_mollie.ps8.PaymentTestsOrdersAPI.js
> E2E: Changed payment method names

- src/ServiceProvider/BaseServiceProvider.php
| Branch?         | release-6.2.5
| Description?    | Upgrade fix
| How to test?    | Upgrade it
| Fixed issue ?   |Fixed upgrade failure `Alias of class not found`
> INTERNAL upgrade fix

- changelog.md
- views/templates/admin/_configure/helpers/form/form.tpl
| Branch?         | Release-6.2.5
| Description?    | typos fixed in changelog and escaping removed as it is escaped previously. 
| How to test?    | --
| Fixed issue ?   | --
> INTERNAL typos fixed in changelog and escaping removed

- upgrade/Upgrade-6.2.5.php
> BUGFIX upgrade table lang

- .github/workflows/create_zip.yml
> INTERNAL actions zip

- changelog.md
- mollie.php
> INTERNAL changelog

- .github/.htaccess
> INTERNAL add .htaccess in .github folder

- controllers/front/webhook.php
- src/Service/MolliePaymentMailService.php
- src/Service/OrderStatusService.php
- src/Service/PaymentMethodService.php
- src/Service/TransactionService.php
- src/Utility/SecureKeyUtility.php
| Branch?         | release-6.2.6
| Description?    | Fixed Klarna double statuses issues when external module assigns other status beside webhook
| How to test?    | You need external module which assigns other status beside webhook (carrier etc.)
| Fixed issue ?   | PIPRES-527 #1025 #1016
> PIPRES-527 Klarna double statuses

- src/Service/MollieOrderCreationService.php
| Branch?         | Release-6.2.6
| Description?    | Before this on exception it was thrown on screen
| How to test?    | Checkout riverty with bad number or address
| Fixed issue ?   |
> INTERNAL fix exception onscreen

- changelog.md
> INTERNAL changelog 6.2.6

- controllers/front/return.php
| Description?    | Fixed mentioned issue
| How to test?    | With debug mode go to checkout process 
| Fixed issue ?   | ![image](https://github.com/user-attachments/assets/64e0d30d-9ced-4cf1-b535-523a26f19b7e)
> INTERNAL fix undefined array keys

- .github/workflows/test.yml
> INTERNAL update `actions/upload-artifact` action

- .github/workflows/test.yml
- controllers/admin/AdminMollieLogsController.php
- controllers/admin/AdminMollieSettingsController.php
- controllers/front/ajax.php
- controllers/front/applePayDirectAjax.php
- controllers/front/payment.php
- controllers/front/recurringOrderDetail.php
- controllers/front/return.php
- controllers/front/subscriptionUpdateWebhook.php
- controllers/front/subscriptionWebhook.php
- controllers/front/webhook.php
- mollie.php
- src/Action/CreateOrderPaymentFeeAction.php
- src/Action/UpdateOrderTotalsAction.php
- src/Controller/AbstractMollieController.php
- src/Controller/AdminMollieEmailController.php
- src/Handler/ErrorHandler/ErrorHandler.php
- src/Handler/Order/OrderCreationHandler.php
- src/Handler/Order/OrderPaymentFeeHandler.php
- src/Service/MollieOrderInfoService.php
- src/Service/PaymentMethod/PaymentMethodRestrictionValidation.php
- src/Service/SettingsSaveService.php
- src/Service/TransactionService.php
- subscription/Action/CreateRecurringOrderAction.php
- subscription/Action/CreateRecurringOrdersProductAction.php
- subscription/Action/UpdateRecurringOrderAction.php
- subscription/Action/UpdateSubscriptionAction.php
- subscription/Handler/RecurringOrderHandler.php
- subscription/Handler/UpdateSubscriptionCarrierHandler.php
| Description?    | Expanded logging
| Type?           | improvement
| How to test?    | Use debug mode
| Fixed issue ?   |
> INTERNAL expand logging

- src/Adapter/Context.php
- src/Builder/FormBuilder.php
- src/Collector/ApplePayDirect/OrderTotalCollector.php
- src/Entity/MolPaymentMethod.php
- src/Factory/ContextFactory.php
- src/Handler/Exception/OrderExceptionHandler.php
- src/Handler/Order/OrderCreationHandler.php
- src/Utility/PsVersionUtility.php
> INTERNAL refactoring notes

- changelog.md
- src/Builder/FormBuilder.php
| Branch?         | develop
| Description?    | Changed TEST / LIVE API Keys alignment & fixed some CS lint
| How to test?    | Go to BO and :eyes: 
| Fixed issue ?   | [PIPRES-543](https://mollie.atlassian.net/browse/PIPRES-543)
[PIPRES-543]: https://mollie.atlassian.net/browse/PIPRES-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIPRES-543 change API keys input alignment

- views/templates/front/mollie_wait.tpl
| Branch?         | develop
| Description?    | Made longer time for customer to wait for order because webhook can delay more than 15s sometimes
| Type?           | bug fix / improvement
| How to test?    | Checkout :shopping_cart: 
| Fixed issue ?   | [PIPRES-540](https://mollie.atlassian.net/browse/PIPRES-540)
[PIPRES-540]: https://mollie.atlassian.net/browse/PIPRES-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIPRES-540 longer order waiting

- src/Config/Config.php
| Branch?         | release-6.2.6
| Description?    | Added new payment method: Multibanco
| Type?           | new feature
| How to test?    | Try it on checkout
| Fixed issue ?   | [PIPRES-524](https://mollie.atlassian.net/browse/PIPRES-524)
[PIPRES-524]: https://mollie.atlassian.net/browse/PIPRES-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIPRES-524 new payment method: Multibanco

- controllers/front/ajax.php
| Description?    | Fixed an issue when surcharge fees on payment method not updates cart total
| How to test?    | Use several payment methods with and without fees
| Fixed issue ?   | [PIPRES-547](https://mollie.atlassian.net/browse/PIPRES-547)
[Screencast From 2025-02-27 07-58-36.webm](https://github.com/user-attachments/assets/7a83a3cd-3715-4db1-9a88-a8f7a9159b57)
[PIPRES-547]: https://mollie.atlassian.net/browse/PIPRES-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIPRES-547 fix payment fees not showing correctly

- changelog.md
> Changelog 6.2.7

- Makefile
> fix zip creation

- changelog.md
- controllers/front/return.php
- mollie.php
> PIPRES-536 Change failed flow redirect place

- changelog.md
- src/Adapter/ProductAttributeAdapter.php
> PIPRES-557 Change Attribute class checking

- controllers/admin/AdminMollieSettingsController.php
> PIPRES-560 ps_accounts undefined method error

- mollie.php
> PIPRES-561 "duplicate entry" install fix

- controllers/front/return.php
| Branch?         | develop
| Description?    | Fixes issue #1087 specific module/theme, etc. Feel free to add more information below this table.
| Type?           | bug fix 
| How to test?    |
| Fixed issue ?   | #1087
> fixes issue #1087

- changelog.md
- mollie.php
- src/Controller/AbstractMollieController.php
- src/Exception/Code/ExceptionCode.php
- src/Provider/PaymentFeeProvider.php
- src/Provider/PaymentOption/IdealPaymentOptionProvider.php
- tests/Unit/Provider/PaymentFeeProviderTest.php
| Description?    | Unessecary logging throwing errors made to debug to not confuse users
| Type?           | bug fix / improvement 
| How to test?    |
| Fixed issue ?   | [PIPRES-555](https://mollie.atlassian.net/browse/PIPRES-555)
[PIPRES-555]: https://mollie.atlassian.net/browse/PIPRES-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIPRES-555 mollie log spam

- src/Service/ApiService.php
| Description?    | Trustly called "Pay by Bank", so we renamed it to be "Pay by Bank (Trustly)"
> PIPRES-559 trustly rename in BO

- mollie.php
| Description?    | Logical error when checking versions
> INTERNAL minor fixes when checking PrestaShop version

- changelog.md
- mollie.php
> 6.2.8 release repare

- README.md
- README_DE.md
- README_ES.md
- README_FR.md
- README_NL.md
| Description?    | More clarity to readme about mollie module compatibility with prestashop versions
| Type?           | improvement
| How to test?    | :eyes: 
| Fixed issue ?   | #1096
> PIPRES-573 update readme

- shared/Core/Shared/Repository/index.php
- shared/Core/Shared/index.php
- shared/Core/index.php
- shared/Infrastructure/Exception/index.php
- shared/Infrastructure/Repository/index.php
- shared/Infrastructure/index.php
- shared/index.php
- src/Infrastructure/index.php
- views/js/admin/cloudsync.js
- views/templates/admin/cloudsync.tpl
- views/templates/admin/dependency_builder.tpl
> INTERNAL validator 6.2.8

- shared/Core/Shared/Repository/index.php
- shared/Core/Shared/index.php
- shared/Core/index.php
- shared/Infrastructure/Exception/index.php
- shared/Infrastructure/Repository/index.php
- shared/Infrastructure/index.php
- shared/index.php
- views/js/admin/cloudsync.js
- views/templates/admin/cloudsync.tpl
- views/templates/admin/dependency_builder.tpl
> Release 6.2.8

- mollie.php
| Description?    | Fixed payment method sorting problem
| How to test?    | Self-explainable
| Fixed issue ?   | https://mollie.atlassian.net/browse/PIPRES-575
> PIPRES-575 payment method sorting fix

- changelog.md
- mollie.php
| Branch?         | Release 6.2.8.1
| Description?    | Hotfix for payment sorting
| How to test?    |
| Fixed issue ?   |
> RELEASE 6.2.8.1

- mollie.php
- src/Service/CartLinesService.php
- src/Utility/TextFormatUtility.php
- tests/Unit/Service/CartLinesServiceTest.php
> PIPRES-576 Remove unsupported characters in Product URL

- changelog.md
- src/Service/CartLinesService.php
> INTERNALchangelog updated

- controllers/front/payment.php
- controllers/front/return.php
- src/Config/Config.php
| Description?    | Due to possible delay for transfer different behavior is needed. Order on prestashop created before successfull payment
> PIPRES-586/ paybybank works like banktransfer

- src/ServiceProvider/BaseServiceProvider.php
| Description?    | Apple pay direct wasnt working because of missing argument. Now it works fine.
| How to test?    | Use apple device with apple pay direct on mollie and it shoudn't throw errors
| Fixed issue ?   | [PIPRES-594](https://mollie.atlassian.net/browse/PIPRES-594)
[PIPRES-594]: https://mollie.atlassian.net/browse/PIPRES-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIPRES-594 missing argument in ApiServiceInterface

- changelog.md
- src/Adapter/ToolsAdapter.php
- src/Handler/Order/OrderCreationHandler.php
- src/Service/CartLinesService.php
- src/Service/PaymentFeeTextService.php
- src/Service/TransactionService.php
- subscription/Presenter/RecurringOrdersPresenter.php
| Description?    | Added payment fee information on order-confirmation page
| Type?           | improvement
| How to test?    | Do checkout with payment fees on various payment methods
| Fixed issue ?   | [PIPRES-592](https://mollie.atlassian.net/browse/PIPRES-592)
[PIPRES-592]: https://mollie.atlassian.net/browse/PIPRES-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIPRES-592 surcharges appearance

- views/js/front/payment_fee.js
| Description?    | Fixed an issue when only one payment method is showing in checkout and there is a fee. Before fix it wasn't calculating. Its only calculated when changing between multiple payment options
| How to test?    | use one paymente method or multiple and see does fee add or not
| Fixed issue ?   |
> BUGFIX payment fee not adding when one payment method in checkout

- src/Verification/Shipment/CanSendShipment.php
> PIPRES-597 regular payment error message edit

- changelog.md
- src/Config/Config.php
> PIPRES-609 payment method Bizum

- subscription/Config/Config.php
- subscription/Provider/SubscriptionIntervalProvider.php
- subscription/Provider/SubscriptionStartDateProvider.php
- tests/Integration/Subscription/Validator/CanProductBeAddedToCartValidatorTest.php
- tests/Integration/Subscription/Validator/SubscriptionOrderValidatorTest.php
- tests/Integration/Subscription/Validator/SubscriptionProductValidatorTest.php
- tests/Unit/Subscription/Provider/SubscriptionIntervalTest.php
| Description?    | Added "Quarterly" into subscriptions
| Type?           | new feature
| How to test?    | 
| Fixed issue ?   | #1139
> PIPRES-610 add "Quarterly" option to subscriptions

- changelog.md
> INTERNAL changelog 6.3.0

- changelog.md
- controllers/admin/AdminMollieAjaxController.php
- mollie.php
- src/Calculator/PaymentFeeCalculator.php
- src/Provider/PaymentFeeProvider.php
- src/Provider/PaymentFeeProviderInterface.php
- src/Provider/PaymentOption/BancontactPaymentOptionProvider.php
- src/Provider/PaymentOption/BasePaymentOptionProvider.php
- src/Provider/PaymentOption/CreditCardPaymentOptionProvider.php
- src/Provider/PaymentOption/CreditCardSingleClickPaymentOptionProvider.php
- src/Provider/PaymentOption/IdealPaymentOptionProvider.php
- tests/Unit/Calculator/PaymentFeeCalculatorTest.php
- tests/Unit/Provider/PaymentFeeProviderTest.php
- views/js/admin/settings.js
- views/templates/admin/_configure/helpers/form/form.tpl
| Description?    | Feature request to allow negative payment fess (like discounts) to encourage one or other payment method for customers
| Type?           | new feature
| How to test?    | Use payment fees
| Fixed issue ?   | #1141
> PIPRES-614 allow negative payment fees

- changelog.md
- src/Config/Config.php
> PIPRES-609 add Bizum payment method

- changelog.md
- mollie.php
- src/Provider/PaymentFeeProvider.php
- views/js/admin/settings.js
- views/templates/admin/_configure/helpers/form/form.tpl
> PIPRES-614 revert negative fees

- changelog.md
- controllers/front/payment.php
- controllers/front/return.php
- mollie.php
- src/Adapter/ToolsAdapter.php
> `Develop` -> `release-6.3.1`

- changelog.md
> Release 6.3.1

- .github/workflows/test.yml
- mollie.php
- src/Adapter/ToolsAdapter.php
> INTERNAL fix cs-fixer
