mollie/controllers/front/payment.php
Use the parameter "billingEmail" when creating the payment, so the customer receives an email when the payment method is banktransfer.
=> Send email address to Mollie for banktransfer payments

.travis.yml, composer.json
The default installed version of PhpUnit for PHP 7.0 and 7.1 is
incompatible with our tests, so build with a hardcoded version of
PhpUnit.
=> Fix the Travis build

.gitignore, controllers/front/return.php
Prestashop 1.7.2.4 will report that the mollie_return.tpl file is missing when not using module: for the filename. This causes an error in development mode.
=> Fix for missing template error

src/Service/TransactionService.php
Fixed an issue when a user customer buys a product that has 0 quantity in stock the status becomes "Payment accepted".
With this fix status "On backorder (paid)" is being set when a customer buys product with 0 qty
=> MOLIM-233 backorder status fix when buying product with 0qty

src/Adapter/ConfigurationAdapter.php, src/Install/Installer.php
Configuration adapter was not used for checking if order state was installed. Also modified adapter to get id shop and id shop group from context if not passed. This issue persisted only on multishop as legacy configuration class automatically sets id shop and id shop group if multishop is deactivated.
Also found weird config setter when exactly same configuration item is being set after it was set in order state install.
=> PIPRES-180: Order state duplication on reset fix

subscription/Handler/CustomerAddressUpdateHandler.php, subscription/Install/HookInstaller.php, subscription/Traits/HookTraits.php
improved whole logic: deleteAfter hook creates copy address, which is saved by another hook into recurring_order table. AddAfter hook replaces recurring_order address with the new one and updateAfter just updates date_updated.
Cases:
- If address is being updated for the first time, soft delete is triggered (address was linked with ps order) and addAfter hook is called (as new address is created)
- If address is being updated not the first time and it was not used in ps order: updateAfter will just update date_updated as Id didn't change.
- If address is being deleted, we let delete it and from the old object we re-create address, which is saved by addAfter hook into recurring_order table.
=> PIPRES-213: Subscription address delete fix

mollie.php, src/Utility/PsVersionUtility.php, subscription/Install/HookInstaller.php, tests/Unit/Utility/PsVersionUtilityTest.php, views/js/front/subscription/product.js
Problem: existing logic for denying product for adding it to the cart (making it available_for_order = false) doesn't work for 1.7.6 version as ps_shoppingcart still shows added to cart modal with no actual added product to cart.
Issue persists only on 1.7.6 version, due to ps_shoppingcart.js file not checking if updateCart emitted action has any errors inside. ps_shoppingcart shows "added to cart" modal, even though operation failed. 
Tested solution on 1.7.6, 1.7.7, 1.7.8
=> PIPRES-214: Stop add to cart action on subscription product fix

controllers/front/subscriptionWebhook.php, subscription/Validator/CanProductBeAddedToCartValidator.php
On cart duplicate, updateQty method is called. In mollie.php we use `hookActionCartUpdateQuantityBefore` to validate if product can be added to cart. This validation is only needed when customer is manipulating cart. But subscription duplicate functionality already duplicates valid cart so we needed to avoid this check.
=> PIPREs-213: Subscription duplicate cart validaor improvements

upgrade/Upgrade-6.0.0.php
Previous SQL call failed due to several reasons:
- Without specifying table_schema (db name), query tries to check other PrestaShop databases if there are ones.
- execute() returns bool of result. But result was not straight value, it was key->value pair so it always failed. getValue returns first row's value so now it gives us correct result.
=> PIPRES-217: Upgrade SQL file issue fix

upgrade/Upgrade-6.0.0.php
After upgrade old controller tabs stayed in the database, causing duplicate menu items. Manually removing it before registering new tabs.
On 1.7.6. authorization_roles table was causing issues as on this specific presta version there is no check before if such entries exist. Inserting on top of it caused exceptions.
=> PIPRES-217: Duplicating menu tabs on upgrade fix

controllers/admin/AdminMollieSettingsController.php
For some reason messages were deleted and errors were thrown due to missing variables.
=> PIPRES-226: Max amount error message fix

controllers/admin/AdminMollieAjaxController.php, controllers/front/ajax.php, src/Controller/AbstractMollieController.php, src/Provider/PaymentOption/BancontactPaymentOptionProvider.php, src/Provider/PaymentOption/BasePaymentOptionProvider.php, src/Provider/PaymentOption/CreditCardPaymentOptionProvider.php, src/Provider/PaymentOption/CreditCardSingleClickPaymentOptionProvider.php, src/Provider/PaymentOption/IdealPaymentOptionProvider.php, src/ServiceProvider/BaseServiceProvider.php, views/js/front/payment_fee.js
Improved ajax call to provide order summary block with updated tax price as well. Previously, only total price was updated.
Also improved overall functionality. Instead of relying on given payment fee from front-end, trying to fetch it fresh from the database.
Payment fee prices are shown with tax incl. Tax is 21%. So 12.10 is 10 without tax.
=> PIPRES-65: tax append to cart summary improvements

controllers/front/payment.php, mollie.php, src/Exception/ShipmentCannotBeSentException.php, src/Handler/Shipment/ShipmentSenderHandler.php, src/Handler/Shipment/ShipmentSenderHandlerInterface.php, src/Logger/PrestaLogger.php, src/Logger/PrestaLoggerInterface.php, src/Service/ExceptionService.php, src/Service/Shipment/ShipmentInformationSender.php, src/Service/Shipment/ShipmentInformationSenderInterface.php, src/Service/TransactionService.php, src/ServiceProvider/BaseServiceProvider.php, src/Verification/IsPaymentInformationAvailable.php, src/Verification/Shipment/CanSendShipment.php, src/Verification/Shipment/ShipmentVerificationInterface.php, tests/Unit/Handler/Shipment/ShipmentSenderHandlerTest.php, tests/Unit/Verification/Shipment/CanSendShipmentTest.php
Use case:
When order is created and initial order state is given for order, updateOrderStatus hook is called. On this hook we try to send shipment. CanSendShipment checks if all requirements are met. But on initial order status update requirements won't be met as orderId is still not returned from validateOrder method, so it is not inserted inside database with mollie transaction. Merchants were annoyed with logged warnings and errors every time order was made from this exact verification. 
That's why we created additional verify service, which is used outside canSendShipment. We use this service to verify if payment information is available by trying to find it by order id.
=> PIPRES-191: Misleading exception throw on shipment verification

controllers/front/payment.php, src/DTO/PaymentFeeData.php, src/Handler/Order/OrderCreationHandler.php, src/Handler/Order/OrderFeeHandler.php, src/Provider/PaymentFeeProvider.php, src/Service/CartLinesService.php, src/Service/OrderFeeService.php, src/Service/PaymentMethodService.php, tests/Unit/Provider/PaymentFeeProviderTest.php, tests/Unit/Service/CartLinesServiceTest.php
Previously payment fee tax incl was appended to  order_total_tax_incl and order_total_tax_excl. Now added tax excl price separately.
Prices and taxes with no payment fee:
Prices with payment fee:
Order summary with tax appended:
Invoice with payment fee (product without tax and with tax sum is 35.61):
FYI: noticed in invoice that there is additional "payment fee" field, which is empty. I'll try to fix it in another PR as more investigation is needed.
=> PIPRES-266: payment fee order tax append

upgrade/Upgrade-6.0.1.php
In upgrade files function names can't repeat as process will break during file import with "include" function.
=> PIPRES-269: Upgrade process fix

.github/workflows/upgrading_check.yml, Makefile
because 5.2.0 was incompatible with PS8x
=> E2E fix upgrading tests

controllers/front/subscriptionWebhook.php, src/Exception/Code/ExceptionCode.php, src/Exception/MollieException.php, src/Handler/Exception/CouldNotHandleOrderPaymentFee.php, src/Handler/Order/OrderPaymentFeeHandler.php, src/Repository/CartRepository.php, src/Repository/CartRepositoryInterface.php, src/Service/OrderPaymentFeeService.php, src/ServiceProvider/BaseServiceProvider.php, subscription/Exception/CouldNotHandleRecurringOrder.php, subscription/Exception/ExceptionCode.php, subscription/Handler/RecurringOrderHandler.php, tests/Unit/Handler/Order/OrderPaymentFeeHandlerTest.php
Fixed issue where payment fee was not appended to recurring orders at all. Logic: fetching payment fee from original order, appending payment fee to duplicated order totals, inserting new payment fee record for the new order.
=> PIPRES-208: Payment fee append to subscription recurred order

mollie.php
Context doesn't always provide us with current locale so we need to retrieve it via Symfony's DI service. It would be a waste to create our locale repository to do this as quite some dependencies are needed there in repository.
=> PIPRES-303: Locale retrieve fix for email template

src/Service/TransactionService.php
Main issue is that for bank transfer order state is not changed when Payment API is used. 
Firstly, other payment options are handled in different way than bank transfer. Bank transfer's order is created before redirecting to Mollie while other methods force order creation only after webhook call, where order state is actually changed. After bank transfer actions webhook is called as well, but it doesn't use the same flow as other method (due to already created order).
Secondly, bank transfer with Order API works fine because there is no additional if statement to check something. After many nested if, elseif, else statements order state change is executed if order is not modified, is not Klarna order. 
After these results investigated previous commits where I found out that for some …
=> PIPRES-221: Bank transfer order state change for payment API fix

src/Adapter/ToolsAdapter.php, subscription/Grid/SubscriptionGridDefinitionFactory.php, subscription/Grid/SubscriptionGridQueryBuilder.php, subscription/Presenter/RecurringOrdersPresenter.php, tests/phpstan/phpstan_base.neon, views/templates/front/subscription/customerSubscriptionsData.tpl
Fixed price display issue. Prices were fetched by calculating product base price instead of full order price.
=> PIPRES-311: Subscription orders table data fix

composer.json, src/Repository/CustomerRepository.php, src/Repository/CustomerRepositoryInterface.php, src/Service/PaymentMethod/PaymentMethodRestrictionValidation/ApplePayPaymentMethodRestrictionValidator.php, src/Service/PaymentMethod/PaymentMethodRestrictionValidation/B2bPaymentMethodRestrictionValidator.php, src/ServiceProvider/BaseServiceProvider.php, tests/Integration/Factory/AddressFactory.php, tests/Integration/Factory/CarrierFactory.php, tests/Integration/Factory/CartFactory.php, tests/Integration/Factory/CustomerFactory.php, tests/Integration/Factory/FactoryInterface.php, tests/Integration/Service/PaymentMethod/PaymentMethodRestrictionValidation/B2bPaymentMethodRestrictionValidatorTest.php
Added validation for Billie payment method. Payment method requirements:
- B2B enabled
- Vat number entered
- Identification number entered
Additionally bumped Mollie vendor package version as Billie was introduced later as we will use constant from the package for saving it in our configs.
=> PIPRES-113: Billie payment method validation

mollie.php, src/Builder/FormBuilder.php, src/Config/Config.php, src/Handler/Order/OrderCreationHandler.php, src/Install/OrderStateInstaller.php, src/Service/ConfigFieldService.php, src/Service/OrderStatusService.php, src/Service/SettingsSaveService.php, src/Service/TransactionService.php, src/Validator/OrderConfMailValidator.php, tests/Integration/Install/OrderStateInstallerTest.php, tests/Unit/Service/PaymentMethod/PaymentMethodRestrictionValidation/VersionSpecificPaymentRestrictionValidationTest.php, upgrade/Upgrade-4.2.0.php, upgrade/Upgrade-6.0.3.php, views/templates/admin/invoice_description.tpl
As Billie payment method will have same actions as Klarna, we needed to use general naming for such methods. Renamed every const, variable, changed order status names and configuration values.
=> PIPRES-113: Billie payment method setup

src/Adapter/Context.php, src/DTO/Object/Company.php, src/DTO/Object/Payment.php, src/DTO/OrderData.php, src/Service/PaymentMethod/PaymentMethodRestrictionValidation/B2bPaymentMethodRestrictionValidator.php, src/Service/PaymentMethodService.php
Additional info about company based on docs: https://docs.mollie.com/reference/v2/orders-api/create-order#payment-parameters
Inside jsonSerialize calling other jsonSerialize methods because we are using Mollie's package, which accepts request data as array. It is not json_encoded.
=> PIPRES-113: Billie payment method additional data send

mollie.php, subscription/Install/HookInstaller.php, upgrade/Upgrade-6.0.4.php
Warning messages appear on PS8.
=> PIPRES-316: hookActionFrontControllerAfterInit replacement on deprecated versions

mollie.php, src/Adapter/ConfigurationAdapter.php, src/Adapter/Context.php, src/Adapter/ToolsAdapter.php, src/Service/CartLinesService.php, src/Service/SettingsSaveService.php, subscription/Install/AttributeInstaller.php, subscription/Install/AttributeUninstaller.php, tests/Integration/BaseTestCase.php, tests/Unit/Service/CartLinesServiceTest.php, tests/Unit/Validator/VoucherValidatorTest.php
* PIPRES-306: Configuration updateValue multishop context fix
=> Hotfix-6.0.4

controllers/front/recurringOrderDetail.php, controllers/front/subscriptions.php, src/Install/DatabaseTableInstaller.php, src/Install/DatabaseTableUninstaller.php, src/Service/MailService.php, subscription/Entity/MolRecurringOrder.php, subscription/Factory/CreateSubscriptionDataFactory.php, subscription/Grid/SubscriptionGridDefinitionFactory.php, subscription/Grid/SubscriptionGridQueryBuilder.php, subscription/Handler/SubscriptionCreationHandler.php, subscription/Install/DatabaseTableInstaller.php, subscription/Presenter/OrderPresenter.php, subscription/Presenter/RecurringOrderLazyArray.php, subscription/Presenter/RecurringOrderPresenter.php, subscription/Presenter/RecurringOrdersPresenter.php, tests/Integration/Subscription/Presenter/OrderPresenterTest.php, tests/bootstrap.php, upgrade/Upgrade-6.0.4.php
Added alter table improvements for install process as following tables are not being removed during uninstall process at all so there were several merchants, which had previously installed Mollie module and came back to install it after some time. Due to this flow some columns were not appended as no upgrade script was executed.
Improvements for subscription order listing in BO and FO.
In BO instead of unit_price started showing total order price. Additionally changed email data for total price.
In FO improved subscriptions order listing to show only subscription order total price (previously full mixed order price was shown)
In FO added decorated OrderLazyArray class and changed OrderProvider to give only products and totals for subscription context. Adding example of recurring order, …
=> PIPRES-338: Mixed cart subscription listing improvements

src/Adapter/Shop.php, subscription/Controller/Symfony/SubscriptionController.php
=> PIPRES-261: Restrict BO subscription list for all shops

src/Service/VoucherService.php, src/Validator/VoucherValidator.php
Condition was always false as comparison was done with strict types while values were never the same type
=> PIPRES-346: Voucher visibility fix

config/routes.yml, config/services.yml, src/Builder/FormBuilder.php, subscription/Controller/Symfony/AbstractSymfonyController.php, subscription/Controller/Symfony/SubscriptionController.php, subscription/Form/ChoiceProvider/CarrierOptionsProvider.php, subscription/Form/Options/SubscriptionOptionsConfiguration.php, subscription/Form/Options/SubscriptionOptionsDataProvider.php, subscription/Form/Options/SubscriptionOptionsType.php, subscription/Handler/RecurringOrderHandler.php, subscription/Logger/Logger.php, views/templates/admin/Subscription/subscriptions-grid.html.twig, views/templates/admin/Subscription/subscriptions-settings.html.twig
=> PIPRES-348: Move subscription options to subscription tab

views/templates/admin/Subscription/subscriptions-settings.html.twig
For lower PS versions noticed that _token is missing in form data and CSRF token error appears. Found out that we were trying to use only subscription_options values for the form.
=> PIPRES-348: Form handler compatibility for lower PS versions

controllers/front/payment.php, controllers/front/return.php, controllers/front/subscriptionUpdateWebhook.php, controllers/front/subscriptionWebhook.php, controllers/front/webhook.php, src/Controller/AbstractMollieController.php, src/Infrastructure/Response/JsonResponse.php, src/Infrastructure/Response/Response.php, src/Logger/PrestaLogger.php, tests/Unit/Factory/SubscriptionDataTest.php
Added lock protection for main front controllers. 
Tested with spam tool to check if controllers resist and lock required resources.
=> PIPRES-319: Webhook controller protection

src/Exception/OrderCreationException.php, src/Handler/Exception/OrderExceptionHandler.php, src/Service/MollieOrderCreationService.php
A new exception type WRONG_FAMILY_NAME has been added to highlight cases when the family name provided in the billing address is incorrect. This exception is triggered from the OrderExceptionHandler. Additionally, fixed the error handling in MollieOrderCreationService to always respond with proper HTTP status codes.
=> PIPRES-425: Add exception handling for incorrect family name

src/Service/ApiService.php
On a fresh prestashop installation 8.1.5 with mollie 6.1.0 installed and iDEAL is active. The ideal bank list on checkout is empty.
```
SELECT * FROM `ps_mol_payment_method_issuer`
0 results.
```
This commit fixes the `ps_mol_payment_method_issuer` table being filled when mollie module settings are saved.
To reproduce the issue for mollie v6.1.0: 
1. empty table with: `TRUNCATE ps_mol_payment_method_issuer` (if table is not empty when upgrading)
2. save mollie settings from module
3. SELECT * FROM `ps_mol_payment_method_issuer`
4. what results in 0 results, no ideal bank issuers information is available.
After adding `'include' => 'issuers'` to 
`$apiMethods = $api->methods->allAvailable(['locale' => '', 'include' => 'issuers']);`
will fix it, and table is being filled with ideal issuers …
=> Fix for adding issuers for iDEAL in table: ps_ol_payment_method_issuer

mollie.php, src/Install/Installer.php, src/Install/Uninstall.php, src/Logger/PrestaLogger.php, subscription/Controller/Symfony/SubscriptionController.php, subscription/Handler/UpdateSubscriptionCarrierHandler.php, subscription/Repository/RecurringOrderRepository.php, subscription/Repository/RecurringOrderRepositoryInterface.php, tests/Unit/BaseTestCase.php, tests/Unit/Subscription/Handler/UpdateSubscriptionCarrierHandlerTest.php
TODO could update this PR with API data mock and integration test this, otherwise test it by hand and debugger as order retrieve query is not yet tested.
=> PIPRES-349: Update subscription carrier handler

controllers/admin/AdminMollieSettingsController.php, src/Builder/FormBuilder.php, src/Config/Config.php, src/Handler/ErrorHandler/ErrorHandler.php, src/Install/Installer.php, src/Install/Uninstall.php, src/Service/ConfigFieldService.php, src/Service/SettingsSaveService.php, upgrade/Upgrade-6.2.0.php, views/templates/admin/mollie-error-logger-modal.tpl, views/templates/admin/mollie_error_logging_info.tpl
=> PIPRES-366/ Sentry error logger consent option addded

src/DTO/OrderData.php
Then phone is optional logic was setting phone field value to N/A which triggers incorrect format.
=> PIPRES-450/phone input validation fix

controllers/front/return.php
Some payment methods upon cancel does not call webhook. Previous message was not informative enough. Added redirection and improved error message to be more understandable. Also added log to be able easily debug this place
=> PIPRES-483 canceled payment error handling

cypress/e2e/ps8/03_mollie.ps8.PaymentTestsOrdersAPI.js
| Branch?         | Release
| Description?    | Changes to e2e tests
| Type?           | refactoring of e2e
=> E2E: Changed payment method names

cypress/e2e/ps8/03_mollie.ps8.PaymentTestsOrdersAPI.js, cypress/e2e/ps8/05_mollie.ps8.PaymentTestsPaymentsAPI.js
=> E2E adjustments: Payment method translations

.github/workflows/create_zip.yml, .github/workflows/test.yml, composer.json, scoper.inc.php, src/ServiceProvider/BaseServiceProvider.php, src/ServiceProvider/LeagueServiceContainerProvider.php, src/ServiceProvider/PrestashopContainer.php, subscription/Install/AttributeInstaller.php
| Branch?         | 6.2.5
| Description?    | Added namespaces to vendor `Psr` and `League` to met Prestashop 9 requirements
| Type?           | Improvement
| How to test?    | Build zip and see if everything works as expected without any critical errors related to namespaces to autoloading
| Fixed issue ?   | -
=> PIPRES-489 php-scoper implementation for vendor namespaces

controllers/front/return.php, views/templates/front/mollie_wait.tpl
| Branch?         | release-6.2.6
| Description?    | Fixed issue with latest mollie API changes that made webhook async.
| How to test?    | Try checkouting with different statuses
| Fixed issue ?   | PIPRES-526
=> BUGFIX async webhook fix

controllers/admin/AdminMollieSettingsController.php
| Description?    | Made cloudsync/ps_account optional in case of error is thrown on those modules.
| Type?           | Improvement
| How to test?    | --
| Fixed issue ?   | --
=> INTERNAL cloudsync screen is optional if error ocurred in dependant modules.

src/Exception/OrderCreationException.php, src/Handler/Exception/OrderExceptionHandler.php, src/Service/ExceptionService.php
| Branch?         | Release-6.2.6
| Description?    | Previously on error then first or second name is incorrect we were throwing default message. These changes will improve error handling and will tell enduser that his first name or family name is incorrect and he must check it.
| Type?           |  improvement
| How to test?    | Checkout with klarna method using one letter as first name or second name.
| Fixed issue ?   | PIPRES-432
=> PIPRES-432 Error message for incorrect first or last name added

src/Config/Config.php
| Branch?         | release-6.2.6
| Description?    | added new payment method: MBway
| Type?           | new feature
| How to test?    | Try it on checkout
| Fixed issue ?   | [PIPRES-523](https://mollie.atlassian.net/browse/PIPRES-523)
[PIPRES-523]: https://mollie.atlassian.net/browse/PIPRES-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIPRES-523 new payment method: MBway
